import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './ui/global.css'
import { GLOBALCONTEXTPROVIDER } from './providers/GlobalContext'
import Header from './ui/Header'
import Footer from './ui/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <GLOBALCONTEXTPROVIDER>
      <html lang='pt-br'>
        <body className={`${inter.className} bg-slate-900`}>
          <Header />
          <main>{children}</main>
          <Footer />
        </body>
      </html>
    </GLOBALCONTEXTPROVIDER>
  )
}
